spring.application.name=LearnFlow

spring.datasource.url=jdbc:mysql://localhost:3306/learnFlowDB
spring.datasource.username=root
spring.datasource.password=manager

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true